# Generated by Django 5.2.17 on 2026-09-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=64, unique=True)),
                ('carrier', models.CharField(choices=[('correios', 'Correios'), ('aliexpress', 'AliExpress'), ('shopee', 'Shopee Xpress'), ('anjun', 'Anjun Express'), ('jtexpress', 'J&T Express'), ('totalexpress', 'Total Express')], db_index=True, max_length=20)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('document', models.CharField(blank=True, help_text='CPF somente dígitos (obrigatório p/ J&T)', max_length=16)),
                ('status_code', models.CharField(blank=True, max_length=64)),
                ('status_label', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('in_transit', 'Em trânsito'), ('delivered', 'Entregue'), ('failed', 'Falha'), ('returned', 'Devolvida'), ('inactive', 'Encerrada')], db_index=True, default='in_transit', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delayed', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('status_key', models.CharField(max_length=128)),
                ('status_label', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trackings.package')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
    ]
