# Generated by Django 5.2.17 on 2026-09-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delay_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='delivered_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
