# Generated by Django 5.2.17 on 2026-09-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackings', '0002_notify_and_reset_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='estimated_delivery',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='last_event_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
