# Generated by Django 5.2.17 on 2026-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackings', '0004_normalize_tracking_code_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='document',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ somente dígitos (obrigatório p/ J&T)', max_length=16),
        ),
    ]
